apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "signet.fullname" . }}-controller
  labels:
    app: {{ include "signet.name" . }}
data:
  controller.yml: |-
{{ .Values.controllerConfig | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "signet.fullname" . }}-policy
  labels:
    app: {{ include "signet.name" . }}
data:
  shield.rego: |-
{{ .Values.regoPolicy | indent 4 }}
