services:
  app:
    build: .
    image: signet-pqc-mvp:latest
    environment:
      - FEATURE_PCH=${FEATURE_PCH:-true}
      - PCH_ADVISORY=${PCH_ADVISORY:-true}
      - REDIS_URL=redis://redis:6379/0
      - DATA_DIR=/app/var/data
      - SERVER_SIGNING_KEY=/app/keys/sth_ed25519_sk.pem
      - CLIENT_KEYS=/app/config/clients.json
  # Enable TLS exporter channel binding end-to-end (Envoy injects x-tls-exporter)
  - BINDING_TYPE=tls-exporter
  - BINDING_HEADER=X-TLS-Exporter
  # Enforce presence of exporter (deny if missing)
  - REQUIRE_TLS_EXPORTER=true
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      # Mount signing keys (private + public) read-only so we can rotate/regenerate without rebuilding image
      - ./keys:/app/keys:ro
      # Mount client key registry / config mapping
      - ./config:/app/config:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  envoy:
    build: ./sandbox/envoy
    image: signet-envoy:latest
    depends_on:
      - app
    # Expose Envoy directly on 8443 now that nginx is removed
    ports:
      - "8443:8443"
    environment:
      - BINDING_TYPE=tls-exporter
    volumes:
      - ./sandbox/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./sandbox/envoy/certs:/etc/envoy/certs:ro
