# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protected.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protected.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotected.proto\x12\x06signet\"#\n\x10ProtectedRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"^\n\x0eProtectedReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x12\n\nreceipt_id\x18\x02 \x01(\t\x12\x14\n\x0cpch_verified\x18\x03 \x01(\x08\x12\x16\n\x0e\x66\x61ilure_reason\x18\x04 \x01(\t2G\n\tProtected\x12:\n\x04\x43\x61ll\x12\x18.signet.ProtectedRequest\x1a\x16.signet.ProtectedReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protected_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTECTEDREQUEST']._serialized_start=27
  _globals['_PROTECTEDREQUEST']._serialized_end=62
  _globals['_PROTECTEDREPLY']._serialized_start=64
  _globals['_PROTECTEDREPLY']._serialized_end=158
  _globals['_PROTECTED']._serialized_start=160
  _globals['_PROTECTED']._serialized_end=231
# @@protoc_insertion_point(module_scope)
